/**
 * @module ModernTemplate
 * @description Modern, clean template for Factur-X invoices
 *
 * Features:
 * - Clean, professional design
 * - Blue color scheme
 * - Clear typography
 * - Optimized for readability
 */

import { TemplateRenderer } from '../core/TemplateRenderer';
import { TemplateType } from '../types';

export class ModernTemplate extends TemplateRenderer {
  protected getTemplateType(): TemplateType {
    return TemplateType.MODERN;
  }

  protected async renderContent(): Promise<void> {
    // Header
    await this.renderHeader();

    // Spacing
    this.renderContext.currentY -= 20;

    // Parties
    this.renderParties();

    // Spacing
    this.renderContext.currentY -= 20;

    // Line items
    this.renderLineItems();

    // Spacing
    this.renderContext.currentY -= 20;

    // Totals
    this.renderTotals();

    // Tax breakdown
    if (this.context.options.showTaxBreakdown) {
      this.renderContext.currentY -= 30;
      this.renderTaxBreakdown();
    }

    // Payment terms
    if (this.context.options.showPaymentTerms) {
      this.renderContext.currentY -= 30;
      this.renderPaymentTerms();
    }

    // Footer
    this.renderFooter();
  }

  /**
   * Render tax breakdown section
   */
  private renderTaxBreakdown(): void {
    const { margins } = this.context.options;
    const { summary } = this.context;
    const startY = this.renderContext.currentY;

    // Title
    this.drawText(this.strings.taxBreakdown, margins.left, startY, {
      size: 12,
      bold: true,
    });

    let y = startY - 25;

    // Header
    this.drawText(this.strings.vatRate, margins.left + 10, y, {
      size: 9,
      bold: true,
    });
    this.drawText(this.strings.taxBase, margins.left + 100, y, {
      size: 9,
      bold: true,
    });
    this.drawText(this.strings.taxAmount, margins.left + 200, y, {
      size: 9,
      bold: true,
    });

    y -= 20;

    // Tax summaries
    for (const taxSum of summary.taxSummaries) {
      this.drawText(`${taxSum.rate}%`, margins.left + 10, y, { size: 9 });
      this.drawText(`${this.formatCurrency(taxSum.taxable)}`, margins.left + 100, y, {
        size: 9,
      });
      this.drawText(`${this.formatCurrency(taxSum.taxAmount)}`, margins.left + 200, y, {
        size: 9,
      });
      y -= 18;
    }

    this.renderContext.currentY = y - 10;
  }

  /**
   * Render payment terms
   */
  private renderPaymentTerms(): void {
    const { margins } = this.context.options;
    const { invoice } = this.context;
    const startY = this.renderContext.currentY;

    // Title
    this.drawText(this.strings.paymentTerms, margins.left, startY, {
      size: 12,
      bold: true,
    });

    let y = startY - 25;

    // Payment means
    if (invoice.payment) {
      this.drawText(
        `${this.strings.paymentMeans}: ${this.getPaymentMeansLabel(invoice.payment.meansCode)}`,
        margins.left + 10,
        y,
        { size: 9 }
      );
      y -= 18;

      if (invoice.payment.iban) {
        this.drawText(`${this.strings.iban}: ${invoice.payment.iban}`, margins.left + 10, y, {
          size: 9,
        });
        y -= 18;
      }

      if (invoice.payment.bic) {
        this.drawText(`${this.strings.bic}: ${invoice.payment.bic}`, margins.left + 10, y, {
          size: 9,
        });
        y -= 18;
      }

      if (invoice.payment.dueDate) {
        this.drawText(
          `${this.strings.dueDate}: ${invoice.payment.dueDate.toLocaleDateString()}`,
          margins.left + 10,
          y,
          { size: 9 }
        );
        y -= 18;
      }

      if (invoice.payment.termsDescription) {
        this.drawText(invoice.payment.termsDescription, margins.left + 10, y, { size: 9 });
        y -= 18;
      }
    }

    this.renderContext.currentY = y - 10;
  }

  /**
   * Render footer
   */
  private renderFooter(): void {
    const { margins, customFooter } = this.context.options;
    const { width } = this.renderContext;
    const { theme } = this.context;

    const footerY = margins.bottom + 20;

    // Footer background
    this.drawRect(margins.left, footerY - 30, width - margins.left - margins.right, 30, {
      fillColor: theme.footerBackground,
    });

    // Page number
    const pageText = `${this.strings.page} ${this.renderContext.pageNumber}`;
    this.drawText(pageText, margins.left + 10, footerY - 18, { size: 8 });

    // Custom footer text
    if (customFooter) {
      const customX = width / 2 - 50;
      this.drawText(customFooter, customX, footerY - 18, { size: 8 });
    }

    // Generated by
    const generatedText = 'Generated by @facturx/templates';
    const generatedX = width - margins.right - 150;
    this.drawText(generatedText, generatedX, footerY - 18, { size: 8 });
  }

  /**
   * Format currency
   */
  private formatCurrency(amount: number): string {
    return amount.toFixed(2) + ' €';
  }

  /**
   * Get payment means label
   */
  private getPaymentMeansLabel(code: number): string {
    const labels: Record<number, string> = {
      1: 'Not defined',
      10: 'Cash',
      20: 'Check',
      30: 'Credit transfer',
      31: 'Debit transfer',
      42: 'Payment to bank account',
      48: 'Bank card',
      49: 'Direct debit',
      57: 'Standing agreement',
      58: 'SEPA credit transfer',
      59: 'SEPA direct debit',
    };
    return labels[code] || `Code ${code}`;
  }
}
